### ISSUE TITLE
Look at using ip instead of ifconfig

### ISSUE THREAD

**Issue by arlake228** [perfsonar/ls-registration-daemon#18]
CentOS 7 does not include ifconfig by default. If teh ip command has everything we need, we can use that, otherwise the CentOS 7 RPM will need to add an ifconfig dependency.

**Comment by mfeit-internet2** [comment]
`ip` is a superset of `ifconfig`, so I'd recommend shifting in that direction.

**Comment by vvidic** [comment]
On Thu, Apr 14, 2016 at 06:50:54AM -0700, Mark Feit wrote:
> `ip` is a superset of `ifconfig`, so I'd recommend shifting in that direction.

This is in perl-shared and should be fixed by this commit:

https://github.com/perfsonar/perl-shared/commit/aa8a7799395ac18b962c254c23fe15fa67632589

-- 
Valentin Vidic
Computer Systems Engineer - Expert
Department of Computer Infrastructure and Services
Croatian Academic and Research Network - CARNet
Josipa Marohnica 5, HR-10000 Zagreb, Croatia
tel: +385 1 6661 714, fax. +385 1 6661 635
gsm: +385 91 2480 919
www.CARNet.hr

**Comment by tonin** [comment]
Maybe we should replace it in there too? https://github.com/perfsonar/toolkit/blob/master/scripts/mod_interface_route

**Comment by arlake228** [comment]
I did a git merge of these changes into master of ls-registration-daemon. Seem to work fine on CentOS 6 as well.

**Comment by arlake228** [comment]
I made a new issue perfsonar/toolkit#120 to address the same issue in mod_interface_route that Antoine mentioned. Closing this one as it seems to be solved in the ls-registration-daemon at least.
