### ISSUE TITLE
Debian: lsregistrationdaemon.conf shouldn't be marked as config file

### ISSUE THREAD

**Issue by tonin** [perfsonar/ls-registration-daemon#32]
During apt-get upgrade process, the `/etc/perfsonar/lsregistrationdaemon.conf` file is flagged as being modified since installation and the upgrade process stop to ask the admin for confirmation of what to do (keep the changed file or take the update file from the package).  The file is managed by the toolkit gui which is directly modifying it.

I think this file shouldn't be marked as config file otherwise auto-update will fail everytime we ship a new version of this file in the package.

**Comment by vvidic** [comment]
On Thu, Jan 19, 2017 at 07:49:18AM -0800, Antoine Delvaux wrote:
> During apt-get upgrade process, the
> `/etc/perfsonar/lsregistrationdaemon.conf` file is flagged as being modified
> since installation and the upgrade process stop to ask the admin for
> confirmation of what to do (keep the changed file or take the update file
> from the package).  The file is managed by the toolkit gui which is directly
> modifying it.
> 
> I think this file shouldn't be marked as config file otherwise auto-update
> will fail everytime we ship a new version of this file in the package.

Right, since all files in /etc get marked as conffiles by default, one
solution would be to move the config to /usr/share/doc/$package/examples.

This also means the service cannot start from postinst anymore since there
would be no default config in /etc.

-- 
Valentin Vidic
Computer Systems Engineer - Expert
Department of Computer Infrastructure and Services
Croatian Academic and Research Network - CARNet
Josipa Marohnica 5, HR-10000 Zagreb, Croatia
tel: +385 1 6661 714, fax. +385 1 6661 635
gsm: +385 91 2480 919
www.CARNet.hr

**Comment by vvidic** [comment]
Fix added to jessie and wheezy branches.

**Comment by tonin** [comment]
Hi Valentin,

Is there any possibility to keep the file in `/etc/perfsonar/` while not marking it as conf file?

**Comment by vvidic** [comment]
On Thu, Jan 26, 2017 at 01:01:14AM -0800, Antoine Delvaux wrote:
> Is there any possibility to keep the file in `/etc/perfsonar/` while not marking it as conf file?

Don't think that would work as the new version of the package would
just overwrite the current contents of the config file with the default
version from the package.

-- 
Valentin Vidic
Computer Systems Engineer - Expert
Department of Computer Infrastructure and Services
Croatian Academic and Research Network - CARNet
Josipa Marohnica 5, HR-10000 Zagreb, Croatia
tel: +385 1 6661 714, fax. +385 1 6661 635
gsm: +385 91 2480 919
www.CARNet.hr
